Add delete Ride to sdk
Cocolis-1/cocolis-js pull request #16
Opened 2023-05-15 10:21 UTC by lcallarec

Hi !

Here's a PR which adds a delete method on rides.

Let me know !

2023-05-15 10:29 UTC, sebfie requested changes
Merci BEAUCOUP pour cette pr. 

Globalement elle est super, j'aurai juste un peu plus blindé la partie test car c'est pas une action anodine le DELETE.

2023-05-15 10:45 UTC, lcallarec commented on src/__tests__/Rides.test.ts
> +    expect(r.status).toStrictEqual(204);
Pour le test qu'il s'agit bien d'un DELETE envoyé, un simple `expect(r.config.method).toStrictEqual("DELETE")` te semble bien ?
Sinon, j'avoue que je ne suis pas habitué à `nock`... Si je rejoue une seconde fois pour avoir un retour en 401, je vais "juste" tester que ma fixture est bien configurée, non ? Ou alors il y a d'autres façons de faire ?

2023-05-15 16:56 UTC, sebfie commented on src/__tests__/Rides.test.ts
> +    expect(r.status).toStrictEqual(204);
Oui moi ca me semblerait bien juste cela, c'est une petite sécurité.
Refaire et avoir une 401 est aussi une bonne idée. A ta convenance, je veux juste qu'on "vérifie" que dans la vraie vie l'annonce a bien été supprimée. Peut etre refaire le delete ce serait parfait

2023-05-17 09:25 UTC, lcallarec commented on src/__tests__/Rides.test.ts
> +    expect(r.status).toStrictEqual(204);
J'ai ajouté des tests.

2023-05-17 09:38 UTC, sebfie commented
Merci, tu peux changer la version dans le package.json en 1.2.0

2023-05-17 10:03 UTC, sebfie commented
Je merge et je vais le faire moi sur develop

2023-05-17 10:03 UTC, merged